# Generated by Django 4.2.17 on 2025-01-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
